# Generated by Django 5.1.6 on 2025-02-26 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetrackerapp', '0002_recurringexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurrence_period',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Transport', 'Transport'), ('Rent', 'Rent'), ('Entertainment', 'Entertainment'), ('bills', 'Bills'), ('Others', 'Others')], default='Others', max_length=20),
        ),
    ]
