# Generated by Django 5.1.6 on 2025-02-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensetrackerapp', '0005_rename_user_id_expense_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='user_id',
            new_name='user',
        ),
    ]
