# Generated by Django 5.1.6 on 2025-02-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetrackerapp', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
